In [15]:
# check files in county_health_rankins

import os
print(os.getcwd())


files = os.listdir('../data/raw/county_health_rankings')
for f in sorted(files):
    print(f)

/Users/douglas/Documents/GitHub/SDOH_Housing_Health_CA/notebooks
2016 County Health Rankings California Data - v3.xls
2017 County Health Rankings California Data - v2.xls
2018 County Health Rankings California Data - v3.xls
2019 County Health Rankings California Data - v1_0.xls
2020 County Health Rankings California Data - v1_0.xlsx
2021 County Health Rankings California Data - v1.xlsx
2022 County Health Rankings California Data - v2.xlsx
2023 County Health Rankings California Data - v3.xlsx
2024 County Health Rankings California Data - v2.xlsx
2025 County Health Rankings California Data - v3.xlsx

In [2]:
import pandas as pd
import numpy as np
import os

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)

Load the 2024 CHR file to inspect structure and confirm availability of outcome 
variables (Premature Death, Preventable Hospital Stays, Poor Mental Health Days) 
that we will later regress on Median Multiple, our measure of housing unaffordability.

In [3]:
# Load 2024 CHR file
file_path = '../data/raw/county_health_rankings/2024 County Health Rankings California Data - v2.xlsx'

df_2024 = pd.read_excel(
    file_path,
    sheet_name='Additional Measure Data',
    header=[0, 1]  # Multi-row header based on what we saw
)

# Inspect
print('Shape:', df_2024.shape)
print('\nColumn names:')
for col in df_2024.columns:
    print(col)

Shape: (59, 344)

Column names:
('Unnamed: 0_level_0', 'FIPS')
('Unnamed: 1_level_0', 'State')
('Unnamed: 2_level_0', 'County')
('Life Expectancy', 'Life Expectancy')
('Life Expectancy', '95% CI - Low')
('Life Expectancy', '95% CI - High')
('Life Expectancy', 'Life Expectancy (Hispanic (all races))')
('Life Expectancy', 'Life Expectancy (Hispanic (all races)) 95% CI - Low')
('Life Expectancy', 'Life Expectancy (Hispanic (all races)) 95% CI - High')
('Life Expectancy', 'Life Expectancy (Non-Hispanic AIAN)')
('Life Expectancy', 'Life Expectancy (Non-Hispanic AIAN) 95% CI - Low')
('Life Expectancy', 'Life Expectancy (Non-Hispanic AIAN) 95% CI - High')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Asian)')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Asian) 95% CI - Low')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Asian) 95% CI - High')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Black)')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Black) 95% CI - Low')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Black) 95% CI - High')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Life Expectancy', 'Life Expectancy (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Life Expectancy', 'Life Expectancy (Non-Hispanic 2+ races)')
('Life Expectancy', 'Life Expectancy (Non-Hispanic 2+ races) 95% CI - Low')
('Life Expectancy', 'Life Expectancy (Non-Hispanic 2+ races) 95% CI - High')
('Life Expectancy', 'Life Expectancy (Non-Hispanic White)')
('Life Expectancy', 'Life Expectancy (Non-Hispanic White) 95% CI - Low')
('Life Expectancy', 'Life Expectancy (Non-Hispanic White) 95% CI - High')
('Premature Age-Adjusted Mortality', '# Deaths')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Death Rate')
('Premature Age-Adjusted Mortality', '95% CI - Low')
('Premature Age-Adjusted Mortality', '95% CI - High')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Hispanic (all races))')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Hispanic (all races)) 95% CI - Low')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Hispanic (all races)) 95% CI - High')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic AIAN)')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic AIAN) 95% CI - Low')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic AIAN) 95% CI - High')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Asian)')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Asian) 95% CI - Low')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Asian) 95% CI - High')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Black)')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Black) 95% CI - Low')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Black) 95% CI - High')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic 2+ races)')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic 2+ races) 95% CI - Low')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic 2+ races) 95% CI - High')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic White)')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic White) 95% CI - Low')
('Premature Age-Adjusted Mortality', 'Age-Adjusted Mortality (Non-Hispanic White) 95% CI - High')
('Child Mortality', '# Deaths')
('Child Mortality', 'Child Mortality Rate')
('Child Mortality', '95% CI - Low')
('Child Mortality', '95% CI - High')
('Child Mortality', 'Child Mortality Rate (Hispanic (all races))')
('Child Mortality', 'Child Mortality Rate (Hispanic (all races)) 95% CI - Low')
('Child Mortality', 'Child Mortality Rate (Hispanic (all races)) 95% CI - High')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic AIAN)')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic AIAN) 95% CI - Low')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic AIAN) 95% CI - High')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Asian)')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Asian) 95% CI - Low')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Asian) 95% CI - High')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Black)')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Black) 95% CI - Low')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Black) 95% CI - High')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic 2+ races)')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic 2+ races) 95% CI - High')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic White)')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic White) 95% CI - Low')
('Child Mortality', 'Child Mortality Rate (Non-Hispanic White) 95% CI - High')
('Infant Mortality', '# Deaths')
('Infant Mortality', 'Infant Mortality Rate')
('Infant Mortality', '95% CI - Low')
('Infant Mortality', '95% CI - High')
('Infant Mortality', 'Infant Mortality Rate (Hispanic (all races))')
('Infant Mortality', 'Infant Mortality Rate (Hispanic (all races)) 95% CI - Low')
('Infant Mortality', 'Infant Mortality Rate (Hispanic (all races)) 95% CI - High')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic AIAN)')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic AIAN) 95% CI - Low')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic AIAN) 95% CI - High')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Asian)')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Asian) 95% CI - Low')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Asian) 95% CI - High')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Black)')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Black) 95% CI - Low')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Black) 95% CI - High')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic 2+ races)')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic 2+ races) 95% CI - High')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic White)')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic White) 95% CI - Low')
('Infant Mortality', 'Infant Mortality Rate (Non-Hispanic White) 95% CI - High')
('Frequent Physical Distress', '% Frequent Physical Distress')
('Frequent Physical Distress', '95% CI - Low')
('Frequent Physical Distress', '95% CI - High')
('Frequent Mental Distress', '% Frequent Mental Distress')
('Frequent Mental Distress', '95% CI - Low')
('Frequent Mental Distress', '95% CI - High')
('Diabetes Prevalence', '% Adults with Diabetes')
('Diabetes Prevalence', '95% CI - Low')
('Diabetes Prevalence', '95% CI - High')
('HIV Prevalence', '# HIV Cases')
('HIV Prevalence', 'HIV Prevalence Rate')
('Food Insecurity', '# Food Insecure')
('Food Insecurity', '% Food Insecure')
('Limited Access to Healthy Foods', '# Limited Access to Healthy Foods')
('Limited Access to Healthy Foods', '% Limited Access to Healthy Foods')
('Drug Overdose Deaths', '# Drug Overdose Deaths')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate')
('Drug Overdose Deaths', '95% CI - Low')
('Drug Overdose Deaths', '95% CI - High')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Hispanic (all races))')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Hispanic (all races)) 95% CI - Low')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Hispanic (all races)) 95% CI - High')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic AIAN)')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic AIAN) 95% CI - Low')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic AIAN) 95% CI - High')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Asian)')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Asian) 95% CI - Low')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Asian) 95% CI - High')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Black)')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Black) 95% CI - Low')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Black) 95% CI - High')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic 2+ races)')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic 2+ races) 95% CI - High')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic White)')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic White) 95% CI - Low')
('Drug Overdose Deaths', 'Drug Overdose Mortality Rate (Non-Hispanic White) 95% CI - High')
('Insufficient Sleep', '% Insufficient Sleep')
('Insufficient Sleep', '95% CI - Low')
('Insufficient Sleep', '95% CI - High')
('Uninsured Adults', '# Uninsured Adults')
('Uninsured Adults', '% Uninsured Adults')
('Uninsured Adults', '95% CI - Low')
('Uninsured Adults', '95% CI - High')
('Uninsured Children', '# Uninsured Children')
('Uninsured Children', '% Uninsured Children')
('Uninsured Children', '95% CI - Low')
('Uninsured Children', '95% CI - High')
('Other Primary Care Providers', 'Other Primary Care Provider Rate')
('Other Primary Care Providers', 'Other Primary Care Provider Ratio')
('High School Graduation', 'Cohort Size')
('High School Graduation', 'High School Graduation Rate')
('Disconnected Youth', '% Disconnected Youth')
('Disconnected Youth', '95% CI - Low')
('Disconnected Youth', '95% CI - High')
('Reading Scores', 'Average Grade Performance')
('Reading Scores', 'Average Grade Performance (AIAN)')
('Reading Scores', 'Average Grade Performance (Asian)')
('Reading Scores', 'Average Grade Performance (Black)')
('Reading Scores', 'Average Grade Performance (Hispanic)')
('Reading Scores', 'Average Grade Performance (White)')
('Math Scores', 'Average Grade Performance')
('Math Scores', 'Average Grade Performance (AIAN)')
('Math Scores', 'Average Grade Performance (Asian)')
('Math Scores', 'Average Grade Performance (Black)')
('Math Scores', 'Average Grade Performance (Hispanic)')
('Math Scores', 'Average Grade Performance (White)')
('School Segregation', 'Segregation Index')
('School Funding Adequacy', 'Spending per Pupil')
('School Funding Adequacy', 'School Funding Adequacy')
('Gender Pay Gap', "Women's Median Earnings")
('Gender Pay Gap', "Men's Median Earnings")
('Gender Pay Gap', 'Gender Pay Gap')
('Gender Pay Gap', '95% CI - Low')
('Gender Pay Gap', '95% CI - High')
('Median Household Income', 'Median Household Income')
('Median Household Income', '95% CI - Low')
('Median Household Income', '95% CI - High')
('Median Household Income', 'Household Income (AIAN)')
('Median Household Income', 'Household Income (AIAN) 95% CI - Low')
('Median Household Income', 'Household Income (AIAN) 95% CI - High')
('Median Household Income', 'Household Income (Asian)')
('Median Household Income', 'Household Income (Asian) 95% CI - Low')
('Median Household Income', 'Household Income (Asian) 95% CI - High')
('Median Household Income', 'Household Income (Black)')
('Median Household Income', 'Household Income (Black) 95% CI - Low')
('Median Household Income', 'Household Income (Black) 95% CI - High')
('Median Household Income', 'Household Income (Hispanic)')
('Median Household Income', 'Household Income (Hispanic) 95% CI - Low')
('Median Household Income', 'Household Income (Hispanic) 95% CI - High')
('Median Household Income', 'Household Income (White)')
('Median Household Income', 'Household Income (White) 95% CI - Low')
('Median Household Income', 'Household Income (White) 95% CI - High')
('Children Eligible for Free or Reduced Price Lunch', '% Enrolled in Free or Reduced Lunch')
('Residential Segregation - Black/White', 'Segregation Index')
('Child Care Cost Burden', '% Household Income Required for Child Care Expenses')
('Child Care Centers', '# Child Care Centers')
('Child Care Centers', 'Child Care Centers per 1,000 Children')
('Homicides', 'Homicide Rate')
('Homicides', '95% CI - Low')
('Homicides', '95% CI - High')
('Homicides', 'Homicide Rate (Hispanic (all races))')
('Homicides', 'Homicide Rate (Hispanic (all races)) 95% CI - Low')
('Homicides', 'Homicide Rate (Hispanic (all races)) 95% CI - High')
('Homicides', 'Homicide Rate (Non-Hispanic AIAN)')
('Homicides', 'Homicide Rate (Non-Hispanic AIAN) 95% CI - Low')
('Homicides', 'Homicide Rate (Non-Hispanic AIAN) 95% CI - High')
('Homicides', 'Homicide Rate (Non-Hispanic Asian)')
('Homicides', 'Homicide Rate (Non-Hispanic Asian) 95% CI - Low')
('Homicides', 'Homicide Rate (Non-Hispanic Asian) 95% CI - High')
('Homicides', 'Homicide Rate (Non-Hispanic Black)')
('Homicides', 'Homicide Rate (Non-Hispanic Black) 95% CI - Low')
('Homicides', 'Homicide Rate (Non-Hispanic Black) 95% CI - High')
('Homicides', 'Homicide Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Homicides', 'Homicide Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Homicides', 'Homicide Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Homicides', 'Homicide Rate (Non-Hispanic 2+ races)')
('Homicides', 'Homicide Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Homicides', 'Homicide Rate (Non-Hispanic 2+ races) 95% CI - High')
('Homicides', 'Homicide Rate (Non-Hispanic White)')
('Homicides', 'Homicide Rate (Non-Hispanic White) 95% CI - Low')
('Homicides', 'Homicide Rate (Non-Hispanic White) 95% CI - High')
('Suicides', '# Deaths')
('Suicides', 'Suicide Rate (Age-Adjusted)')
('Suicides', '95% CI - Low')
('Suicides', '95% CI - High')
('Suicides', 'Crude Rate')
('Suicides', 'Suicide Rate (Hispanic (all races))')
('Suicides', 'Suicide Rate (Hispanic (all races)) 95% CI - Low')
('Suicides', 'Suicide Rate (Hispanic (all races)) 95% CI - High')
('Suicides', 'Suicide Rate (Non-Hispanic AIAN)')
('Suicides', 'Suicide Rate (Non-Hispanic AIAN) 95% CI - Low')
('Suicides', 'Suicide Rate (Non-Hispanic AIAN) 95% CI - High')
('Suicides', 'Suicide Rate (Non-Hispanic Asian)')
('Suicides', 'Suicide Rate (Non-Hispanic Asian) 95% CI - Low')
('Suicides', 'Suicide Rate (Non-Hispanic Asian) 95% CI - High')
('Suicides', 'Suicide Rate (Non-Hispanic Black)')
('Suicides', 'Suicide Rate (Non-Hispanic Black) 95% CI - Low')
('Suicides', 'Suicide Rate (Non-Hispanic Black) 95% CI - High')
('Suicides', 'Suicide Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Suicides', 'Suicide Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Suicides', 'Suicide Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Suicides', 'Suicide Rate (Non-Hispanic 2+ races)')
('Suicides', 'Suicide Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Suicides', 'Suicide Rate (Non-Hispanic 2+ races) 95% CI - High')
('Suicides', 'Suicide Rate (Non-Hispanic White)')
('Suicides', 'Suicide Rate (Non-Hispanic White) 95% CI - Low')
('Suicides', 'Suicide Rate (Non-Hispanic White) 95% CI - High')
('Firearm Fatalities', '# Firearm Fatalities')
('Firearm Fatalities', 'Firearm Fatalities Rate')
('Firearm Fatalities', '95% CI - Low')
('Firearm Fatalities', '95% CI - High')
('Firearm Fatalities', 'Firearm Fatalities Rate (Hispanic (all races))')
('Firearm Fatalities', 'Firearm Fatalities Rate (Hispanic (all races)) 95% CI - Low')
('Firearm Fatalities', 'Firearm Fatalities Rate (Hispanic (all races)) 95% CI - High')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic AIAN)')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic AIAN) 95% CI - Low')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic AIAN) 95% CI - High')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Asian)')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Asian) 95% CI - Low')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Asian) 95% CI - High')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Black)')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Black) 95% CI - Low')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Black) 95% CI - High')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic 2+ races)')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic 2+ races) 95% CI - High')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic White)')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic White) 95% CI - Low')
('Firearm Fatalities', 'Firearm Fatalities Rate (Non-Hispanic White) 95% CI - High')
('Motor Vehicle Crash Deaths', '# Motor Vehicle Deaths')
('Motor Vehicle Crash Deaths', 'Motor Vehicle Mortality Rate')
('Motor Vehicle Crash Deaths', '95% CI - Low')
('Motor Vehicle Crash Deaths', '95% CI - High')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Hispanic (all races))')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Hispanic (all races)) 95% CI - Low')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Hispanic (all races)) 95% CI - High')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Non-Hispanic AIAN)')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Non-Hispanic AIAN) 95% CI - Low')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Non-Hispanic AIAN) 95% CI - High')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Non-Hispanic Asian)')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Non-Hispanic Asian) 95% CI - Low')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Non-Hispanic Asian) 95% CI - High')
('Motor Vehicle Crash Deaths', 'MV Mortality Rate (Non-Hispanic Black)')

Of the potential outcome variables available in the 'Additional Measure Data' 
sheet, Life Expectancy was considered but rejected in favor of Premature Death 
(YPLL — Years of Potential Life Lost), available in the 'Select Measure Data' 
sheet. YPLL weights early deaths more heavily than average life expectancy, 
making it more sensitive to the effects of housing unaffordability and economic 
stress on working-age adults.

From the 'Select Measure Data' sheet, three outcome variables were selected 
for regression against the Median Multiple, our primary measure of housing 
unaffordability: Premature Death (Years of Potential Life Lost Rate), 
Preventable Hospital Stays (Preventable Hospitalization Rate), and Poor 
Mental Health Days (Average Number of Mentally Unhealthy Days). Two additional 
variables — Children in Poverty and Low Birthweight — were identified as 
potential mediators for subsequent mediation analysis.

In [4]:
df_select = pd.read_excel(
    file_path,
    sheet_name='Select Measure Data',
    header=[0, 1]
)

print('Shape:', df_select.shape)
print('\nColumn names:')
for col in df_select.columns:
    print(col)

Shape: (59, 272)

Column names:
('Unnamed: 0_level_0', 'FIPS')
('Unnamed: 1_level_0', 'State')
('Unnamed: 2_level_0', 'County')
('Premature Death', 'Unreliable')
('Premature Death', 'Deaths')
('Premature Death', 'Years of Potential Life Lost Rate')
('Premature Death', '95% CI - Low')
('Premature Death', '95% CI - High')
('Premature Death', 'National Z-Score')
('Premature Death', 'YPLL Rate (Hispanic (all races))')
('Premature Death', 'YPLL Rate (Hispanic (all races)) 95% CI - Low')
('Premature Death', 'YPLL Rate (Hispanic (all races)) 95% CI - High')
('Premature Death', 'YPLL Rate (Hispanic (all races)) Unreliable')
('Premature Death', 'YPLL Rate (Non-Hispanic AIAN)')
('Premature Death', 'YPLL Rate (Non-Hispanic AIAN) 95% CI - Low')
('Premature Death', 'YPLL Rate (Non-Hispanic AIAN) 95% CI - High')
('Premature Death', 'YPLL Rate (Non-Hispanic AIAN) Unreliable')
('Premature Death', 'YPLL Rate (Non-Hispanic Asian)')
('Premature Death', 'YPLL Rate (Non-Hispanic Asian) 95% CI - Low')
('Premature Death', 'YPLL Rate (Non-Hispanic Asian) 95% CI - High')
('Premature Death', 'YPLL Rate (Non-Hispanic Asian) Unreliable')
('Premature Death', 'YPLL Rate (Non-Hispanic Black)')
('Premature Death', 'YPLL Rate (Non-Hispanic Black) 95% CI - Low')
('Premature Death', 'YPLL Rate (Non-Hispanic Black) 95% CI - High')
('Premature Death', 'YPLL Rate (Non-Hispanic Black) Unreliable')
('Premature Death', 'YPLL Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Premature Death', 'YPLL Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Premature Death', 'YPLL Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Premature Death', 'YPLL Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) Unreliable')
('Premature Death', 'YPLL Rate (Non-Hispanic 2+ races)')
('Premature Death', 'YPLL Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Premature Death', 'YPLL Rate (Non-Hispanic 2+ races) 95% CI - High')
('Premature Death', 'YPLL Rate (Non-Hispanic 2+ races) Unreliable')
('Premature Death', 'YPLL Rate (Non-Hispanic White)')
('Premature Death', 'YPLL Rate (Non-Hispanic White) 95% CI - Low')
('Premature Death', 'YPLL Rate (Non-Hispanic White) 95% CI - High')
('Premature Death', 'YPLL Rate (Non-Hispanic White) Unreliable')
('Poor or Fair Health', '% Fair or Poor Health')
('Poor or Fair Health', '95% CI - Low')
('Poor or Fair Health', '95% CI - High')
('Poor or Fair Health', 'National Z-Score')
('Poor Physical Health Days', 'Average Number of Physically Unhealthy Days')
('Poor Physical Health Days', '95% CI - Low')
('Poor Physical Health Days', '95% CI - High')
('Poor Physical Health Days', 'National Z-Score')
('Poor Mental Health Days', 'Average Number of Mentally Unhealthy Days')
('Poor Mental Health Days', '95% CI - Low')
('Poor Mental Health Days', '95% CI - High')
('Poor Mental Health Days', 'National Z-Score')
('Low Birthweight', 'Unreliable')
('Low Birthweight', '% Low Birthweight')
('Low Birthweight', '95% CI - Low')
('Low Birthweight', '95% CI - High')
('Low Birthweight', 'National Z-Score')
('Low Birthweight', '% LBW (Hispanic (all races))')
('Low Birthweight', '% LBW (Hispanic (all races)) 95% CI - Low')
('Low Birthweight', '% LBW (Hispanic (all races)) 95% CI - High')
('Low Birthweight', '% LBW (Non-Hispanic AIAN)')
('Low Birthweight', '% LBW (Non-Hispanic AIAN) 95% CI - Low')
('Low Birthweight', '% LBW (Non-Hispanic AIAN) 95% CI - High')
('Low Birthweight', '% LBW (Non-Hispanic Asian)')
('Low Birthweight', '% LBW (Non-Hispanic Asian) 95% CI - Low')
('Low Birthweight', '% LBW (Non-Hispanic Asian) 95% CI - High')
('Low Birthweight', '% LBW (Non-Hispanic Black)')
('Low Birthweight', '% LBW (Non-Hispanic Black) 95% CI - Low')
('Low Birthweight', '% LBW (Non-Hispanic Black) 95% CI - High')
('Low Birthweight', '% LBW (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Low Birthweight', '% LBW (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Low Birthweight', '% LBW (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Low Birthweight', '% LBW (Non-Hispanic 2+ races)')
('Low Birthweight', '% LBW (Non-Hispanic 2+ races) 95% CI - Low')
('Low Birthweight', '% LBW (Non-Hispanic 2+ races) 95% CI - High')
('Low Birthweight', '% LBW (Non-Hispanic White)')
('Low Birthweight', '% LBW (Non-Hispanic White) 95% CI - Low')
('Low Birthweight', '% LBW (Non-Hispanic White) 95% CI - High')
('Adult Smoking', '% Adults Reporting Currently Smoking')
('Adult Smoking', '95% CI - Low')
('Adult Smoking', '95% CI - High')
('Adult Smoking', 'National Z-Score')
('Adult Obesity', '% Adults with Obesity')
('Adult Obesity', '95% CI - Low')
('Adult Obesity', '95% CI - High')
('Adult Obesity', 'National Z-Score')
('Food Environment Index', 'Food Environment Index')
('Food Environment Index', 'National Z-Score')
('Physical Inactivity', '% Physically Inactive')
('Physical Inactivity', '95% CI - Low')
('Physical Inactivity', '95% CI - High')
('Physical Inactivity', 'National Z-Score')
('Access to Exercise Opportunities', '% With Access to Exercise Opportunities')
('Access to Exercise Opportunities', 'National Z-Score')
('Excessive Drinking', '% Excessive Drinking')
('Excessive Drinking', '95% CI - Low')
('Excessive Drinking', '95% CI - High')
('Excessive Drinking', 'National Z-Score')
('Alcohol-Impaired Driving Deaths', '# Alcohol-Impaired Driving Deaths')
('Alcohol-Impaired Driving Deaths', '# Driving Deaths')
('Alcohol-Impaired Driving Deaths', '% Driving Deaths with Alcohol Involvement')
('Alcohol-Impaired Driving Deaths', '95% CI - Low')
('Alcohol-Impaired Driving Deaths', '95% CI - High')
('Alcohol-Impaired Driving Deaths', 'National Z-Score')
('Sexually Transmitted Infections', '# Chlamydia Cases')
('Sexually Transmitted Infections', 'Chlamydia Rate')
('Sexually Transmitted Infections', 'National Z-Score')
('Teen Births', 'Teen Birth Rate')
('Teen Births', '95% CI - Low')
('Teen Births', '95% CI - High')
('Teen Births', 'National Z-Score')
('Teen Births', 'Teen Birth Rate (Hispanic (all races))')
('Teen Births', 'Teen Birth Rate (Hispanic (all races)) 95% CI - Low')
('Teen Births', 'Teen Birth Rate (Hispanic (all races)) 95% CI - High')
('Teen Births', 'Teen Birth Rate (Non-Hispanic AIAN)')
('Teen Births', 'Teen Birth Rate (Non-Hispanic AIAN) 95% CI - Low')
('Teen Births', 'Teen Birth Rate (Non-Hispanic AIAN) 95% CI - High')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Asian)')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Asian) 95% CI - Low')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Asian) 95% CI - High')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Black)')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Black) 95% CI - Low')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Black) 95% CI - High')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Teen Births', 'Teen Birth Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Teen Births', 'Teen Birth Rate (Non-Hispanic 2+ races)')
('Teen Births', 'Teen Birth Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Teen Births', 'Teen Birth Rate (Non-Hispanic 2+ races) 95% CI - High')
('Teen Births', 'Teen Birth Rate (Non-Hispanic White)')
('Teen Births', 'Teen Birth Rate (Non-Hispanic White) 95% CI - Low')
('Teen Births', 'Teen Birth Rate (Non-Hispanic White) 95% CI - High')
('Uninsured', '# Uninsured')
('Uninsured', '% Uninsured')
('Uninsured', '95% CI - Low')
('Uninsured', '95% CI - High')
('Uninsured', 'National Z-Score')
('Primary Care Physicians', '# Primary Care Physicians')
('Primary Care Physicians', 'Primary Care Physicians Rate')
('Primary Care Physicians', 'Primary Care Physicians Ratio')
('Primary Care Physicians', 'National Z-Score')
('Dentists', '# Dentists')
('Dentists', 'Dentist Rate')
('Dentists', 'Dentist Ratio')
('Dentists', 'National Z-Score')
('Mental Health Providers', '# Mental Health Providers')
('Mental Health Providers', 'Mental Health Provider Rate')
('Mental Health Providers', 'Mental Health Provider Ratio')
('Mental Health Providers', 'National Z-Score')
('Preventable Hospital Stays', 'Preventable Hospitalization Rate')
('Preventable Hospital Stays', 'National Z-Score')
('Preventable Hospital Stays', 'Preventable Hosp. Rate (AIAN)')
('Preventable Hospital Stays', 'Preventable Hosp. Rate (Asian)')
('Preventable Hospital Stays', 'Preventable Hosp. Rate (Black)')
('Preventable Hospital Stays', 'Preventable Hosp. Rate (Hispanic)')
('Preventable Hospital Stays', 'Preventable Hosp. Rate (White)')
('Mammography Screening', '% with Annual Mammogram')
('Mammography Screening', 'National Z-Score')
('Mammography Screening', '% Screened (AIAN)')
('Mammography Screening', '% Screened (Asian)')
('Mammography Screening', '% Screened (Black)')
('Mammography Screening', '% Screened (Hispanic)')
('Mammography Screening', '% Screened (White)')
('Flu Vaccinations', '% Vaccinated')
('Flu Vaccinations', 'National Z-Score')
('Flu Vaccinations', '% Vaccinated (AIAN)')
('Flu Vaccinations', '% Vaccinated (Asian)')
('Flu Vaccinations', '% Vaccinated (Black)')
('Flu Vaccinations', '% Vaccinated (Hispanic)')
('Flu Vaccinations', '% Vaccinated (White)')
('High School Completion', '# Completed High School')
('High School Completion', 'Population')
('High School Completion', '% Completed High School')
('High School Completion', '95% CI - Low')
('High School Completion', '95% CI - High')
('High School Completion', 'National Z-Score')
('Some College', '# Some College')
('Some College', 'Population')
('Some College', '% Some College')
('Some College', '95% CI - Low')
('Some College', '95% CI - High')
('Some College', 'National Z-Score')
('Unemployment', '# Unemployed')
('Unemployment', 'Labor Force')
('Unemployment', '% Unemployed')
('Unemployment', 'National Z-Score')
('Children in Poverty', '% Children in Poverty')
('Children in Poverty', '95% CI - Low')
('Children in Poverty', '95% CI - High')
('Children in Poverty', 'National Z-Score')
('Children in Poverty', '% Children in Poverty (AIAN)')
('Children in Poverty', '% Children in Poverty (Asian)')
('Children in Poverty', '% Children in Poverty (Black)')
('Children in Poverty', '% Children in Poverty (Hispanic)')
('Children in Poverty', '% Children in Poverty (White)')
('Income Inequality', '80th Percentile Income')
('Income Inequality', '20th Percentile Income')
('Income Inequality', 'Income Ratio')
('Income Inequality', 'National Z-Score')
('Children in Single-Parent Households', '# Children in Single-Parent Households')
('Children in Single-Parent Households', '# Children in Households')
('Children in Single-Parent Households', '% Children in Single-Parent Households')
('Children in Single-Parent Households', '95% CI - Low')
('Children in Single-Parent Households', '95% CI - High')
('Children in Single-Parent Households', 'National Z-Score')
('Social Associations', '# Associations')
('Social Associations', 'Social Association Rate')
('Social Associations', 'National Z-Score')
('Injury Deaths', '# Injury Deaths')
('Injury Deaths', 'Injury Death Rate')
('Injury Deaths', '95% CI - Low')
('Injury Deaths', '95% CI - High')
('Injury Deaths', 'National Z-Score')
('Injury Deaths', 'Injury Death Rate (Hispanic (all races))')
('Injury Deaths', 'Injury Death Rate (Hispanic (all races)) 95% CI - Low')
('Injury Deaths', 'Injury Death Rate (Hispanic (all races)) 95% CI - High')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic AIAN)')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic AIAN) 95% CI - Low')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic AIAN) 95% CI - High')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Asian)')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Asian) 95% CI - Low')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Asian) 95% CI - High')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Black)')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Black) 95% CI - Low')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Black) 95% CI - High')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic 2+ races)')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic 2+ races) 95% CI - Low')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic 2+ races) 95% CI - High')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic White)')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic White) 95% CI - Low')
('Injury Deaths', 'Injury Death Rate (Non-Hispanic White) 95% CI - High')
('Air Pollution - Particulate Matter', 'Average Daily PM2.5')
('Air Pollution - Particulate Matter', 'National Z-Score')
('Drinking Water Violations', 'Presence of Water Violation')
('Drinking Water Violations', 'National Z-Score')
('Severe Housing Problems', '% Severe Housing Problems')
('Severe Housing Problems', '95% CI - Low')
('Severe Housing Problems', '95% CI - High')
('Severe Housing Problems', 'Severe Housing Cost Burden')
('Severe Housing Problems', 'Severe Housing Cost Burden 95% CI - Low')
('Severe Housing Problems', 'Severe Housing Cost Burden 95% CI - High')
('Severe Housing Problems', 'Overcrowding')
('Severe Housing Problems', 'Overcrowding 95% CI - Low')
('Severe Housing Problems', 'Overcrowding 95% CI - High')
('Severe Housing Problems', 'Inadequate Facilities')
('Severe Housing Problems', 'Inadequate Facilities 95% CI - Low')
('Severe Housing Problems', 'Inadequate Facilities 95% CI - High')
('Severe Housing Problems', 'National Z-Score')
('Driving Alone to Work', '% Drive Alone to Work')
('Driving Alone to Work', '95% CI - Low')
('Driving Alone to Work', '95% CI - High')
('Driving Alone to Work', 'National Z-Score')
('Driving Alone to Work', '% Drive Alone (AIAN)')
('Driving Alone to Work', '% Drive Alone (AIAN) 95% CI - Low')
('Driving Alone to Work', '% Drive Alone (AIAN) 95% CI - High')
('Driving Alone to Work', '% Drive Alone (Asian)')
('Driving Alone to Work', '% Drive Alone (Asian) 95% CI - Low')
('Driving Alone to Work', '% Drive Alone (Asian) 95% CI - High')
('Driving Alone to Work', '% Drive Alone (Black)')
('Driving Alone to Work', '% Drive Alone (Black) 95% CI - Low')
('Driving Alone to Work', '% Drive Alone (Black) 95% CI - High')
('Driving Alone to Work', '% Drive Alone (Hispanic)')
('Driving Alone to Work', '% Drive Alone (Hispanic) 95% CI - Low')
('Driving Alone to Work', '% Drive Alone (Hispanic) 95% CI - High')
('Driving Alone to Work', '% Drive Alone (White)')
('Driving Alone to Work', '% Drive Alone (White) 95% CI - Low')
('Driving Alone to Work', '% Drive Alone (White) 95% CI - High')
('Long Commute - Driving Alone', '# Workers who Drive Alone')
('Long Commute - Driving Alone', '% Long Commute - Drives Alone')
('Long Commute - Driving Alone', '95% CI - Low')
('Long Commute - Driving Alone', '95% CI - High')
('Long Commute - Driving Alone', 'National Z-Score')

In [5]:
df_select_outcomes = df_select[[('Unnamed: 0_level_0', 'FIPS'),('Unnamed: 2_level_0', 'County'),
('Premature Death', 'Years of Potential Life Lost Rate'), ('Poor Mental Health Days', 'Average Number of Mentally Unhealthy Days'),
('Preventable Hospital Stays', 'Preventable Hospitalization Rate')]]

print(df_select_outcomes.head(3).to_string())

  Unnamed: 0_level_0 Unnamed: 2_level_0                   Premature Death                   Poor Mental Health Days       Preventable Hospital Stays
                FIPS             County Years of Potential Life Lost Rate Average Number of Mentally Unhealthy Days Preventable Hospitalization Rate
0               6000                NaN                       6373.194549                                  4.650926                             2153
1               6001            Alameda                       4981.213394                                  5.070780                             2102
2               6003             Alpine                               NaN                                  5.541764                              921

In [6]:
df_select_mediators = df_select[[('Unnamed: 0_level_0', 'FIPS'),('Unnamed: 2_level_0', 'County'), ('Children in Poverty', '% Children in Poverty'),('Low Birthweight', '% Low Birthweight')]]

print(df_select_mediators)
print(df_select_mediators.head(3).to_string())

   Unnamed: 0_level_0 Unnamed: 2_level_0   Children in Poverty  \
                 FIPS             County % Children in Poverty
0                6000                NaN                  15.3
1                6001            Alameda                  10.3
2                6003             Alpine                  26.6
3                6005             Amador                  12.0
4                6007              Butte                  18.7
5                6009          Calaveras                  16.2
6                6011             Colusa                  13.7
7                6013       Contra Costa                  10.0
8                6015          Del Norte                  22.5
9                6017          El Dorado                   6.5
10               6019             Fresno                  25.1
11               6021              Glenn                  19.2
12               6023           Humboldt                  20.5
13               6025           Imperial                  27.5
14               6027               Inyo                  13.5
15               6029               Kern                  23.6
16               6031              Kings                  21.3
17               6033               Lake                  22.8
18               6035             Lassen                  17.0
19               6037        Los Angeles                  18.1
20               6039             Madera                  31.3
21               6041              Marin                   8.1
22               6043           Mariposa                  21.3
23               6045          Mendocino                  22.6
24               6047             Merced                  26.0
25               6049              Modoc                  28.0
26               6051               Mono                  10.6
27               6053           Monterey                  16.4
28               6055               Napa                   9.3
29               6057             Nevada                  11.8
30               6059             Orange                  11.0
31               6061             Placer                   5.5
32               6063             Plumas                  18.0
33               6065          Riverside                  13.3
34               6067         Sacramento                  15.4
35               6069         San Benito                   8.3
36               6071     San Bernardino                  18.2
37               6073          San Diego                  12.6
38               6075      San Francisco                   7.9
39               6077        San Joaquin                  16.0
40               6079    San Luis Obispo                  10.7
41               6081          San Mateo                   7.2
42               6083      Santa Barbara                  16.1
43               6085        Santa Clara                   6.9
44               6087         Santa Cruz                  12.0
45               6089             Shasta                  15.8
46               6091             Sierra                  13.6
47               6093           Siskiyou                  17.7
48               6095             Solano                  11.7
49               6097             Sonoma                   9.4
50               6099         Stanislaus                  18.5
51               6101             Sutter                  18.0
52               6103             Tehama                  19.3
53               6105            Trinity                  24.4
54               6107             Tulare                  24.3
55               6109           Tuolumne                  15.1
56               6111            Ventura                  12.5
57               6113               Yolo                  14.5
58               6115               Yuba                  19.0

     Low Birthweight
   % Low Birthweight
0           7.053547
1           7.304157
2                NaN
3           5.942433
4           6.237464
5           6.520119
6           6.024096
7           7.158263
8           6.611994
9           6.641194
10          7.488563
11          5.611068
12          6.235985
13          6.045492
14          8.227848
15          7.569969
16          6.613551
17          7.161227
18          8.341014
19          7.386024
20          6.376110
21          5.561358
22          6.969697
23          6.883217
24          6.374604
25          8.466454
26          8.370536
27          6.347166
28          6.031819
29          5.534591
30          6.458649
31          5.823402
32          8.730159
33          7.050337
34          7.104689
35          6.929446
36          7.800938
37          6.806870
38          7.102415
39          7.554252
40          6.204295
41          6.702857
42          6.824229
43          7.160142
44          5.993211
45          6.779788
46         10.055866
47          8.389716
48          7.120787
49          5.903399
50          6.577850
51          6.954056
52          6.322605
53          6.357616
54          7.108709
55          6.594457
56          6.204637
57          6.053614
58          6.780482
  Unnamed: 0_level_0 Unnamed: 2_level_0   Children in Poverty   Low Birthweight
                FIPS             County % Children in Poverty % Low Birthweight
0               6000                NaN                  15.3          7.053547
1               6001            Alameda                  10.3          7.304157
2               6003             Alpine                  26.6               NaN

In [7]:
# drop the state row
df_select_outcomes = df_select_outcomes.drop(index=0)
df_select_mediators = df_select_mediators.drop(index=0)

# check for null values
print(df_select_outcomes.isna().sum())
print(df_select_mediators.isna().sum())

Unnamed: 0_level_0          FIPS                                         0
Unnamed: 2_level_0          County                                       0
Premature Death             Years of Potential Life Lost Rate            2
Poor Mental Health Days     Average Number of Mentally Unhealthy Days    0
Preventable Hospital Stays  Preventable Hospitalization Rate             0
dtype: int64
Unnamed: 0_level_0   FIPS                     0
Unnamed: 2_level_0   County                   0
Children in Poverty  % Children in Poverty    0
Low Birthweight      % Low Birthweight        1
dtype: int64

In [8]:
# check counties impacted by nulls
df_select_outcomes[df_select_outcomes[('Premature Death', 'Years of Potential Life Lost Rate')].isna()]

,Unnamed: 0_level_0,Unnamed: 2_level_0,Premature Death,Poor Mental Health Days,Preventable Hospital Stays
,FIPS,County,Years of Potential Life Lost Rate,Average Number of Mentally Unhealthy Days,Preventable Hospitalization Rate
2,6003,Alpine,NaN,5.541764,921
46,6091,Sierra,NaN,5.482310,1644

In [9]:
df_select_mediators[df_select_mediators[('Low Birthweight', '% Low Birthweight')].isna()]

,Unnamed: 0_level_0,Unnamed: 2_level_0,Children in Poverty,Low Birthweight
,FIPS,County,% Children in Poverty,% Low Birthweight
2,6003,Alpine,26.6,NaN

Null values were observed in two rural counties: Alpine (FIPS 06003) and 
Sierra (FIPS 06091). All county data will be retained in order to preserve 
valid observations for other outcome variables. Null values will be excluded 
listwise at the model level rather than removed from the dataset. This 
approach acknowledges unavoidable data suppression in low-population counties 
as a limitation of the analysis.

In [10]:
# revisit after column naming conventions are understood


# # relevent_variables = ['Unnamed: 0_level_0', 'FIPS','Unnamed: 2_level_0', 'County', 'Premature Death', 'Years of Potential Life Lost Rate', 'Poor Mental Health Days', 'Average Number of Mentally Unhealthy Days',
# # 'Preventable Hospital Stays', 'Preventable Hospitalization Rate','Children in Poverty', '% Children in Poverty','Low Birthweight', '% Low Birthweight']
   
# for f in files:
#     if '2025' in f:
#         continue
#     file_path = '../data/raw/county_health_rankings/' + f
#     df_year = pd.read_excel(
#         file_path,
#         sheet_name='Select Measure Data',
#         header=[0, 1])
#     print('File:', f, '| Shape:', df_year.shape)

In [11]:
for f in files:
    if '2025' in f:
        continue
    file_path = '../data/raw/county_health_rankings/' + f
    xl = pd.ExcelFile(file_path)
    print(f, '|', xl.sheet_names)

2023 County Health Rankings California Data - v3.xlsx | ['Introduction', 'Outcomes & Factors Rankings', 'Outcomes & Factors SubRankings', 'Ranked Measure Data', 'Additional Measure Data', 'Ranked Measure Sources & Years', 'Addtl Measure Sources & Years']
2018 County Health Rankings California Data - v3.xls | ['Introduction', 'Outcomes & Factors Rankings', 'Outcomes & Factors SubRankings', 'Ranked Measure Data', 'Additional Measure Data', 'Ranked Measure Sources & Years', 'Addtl Measure Sources & Years']
2017 County Health Rankings California Data - v2.xls | ['Introduction', 'Outcomes & Factors Rankings', 'Outcomes & Factors SubRankings', 'Ranked Measure Data', 'Additional Measure Data', 'Ranked Measure Sources & Years', 'Addtl Measure Sources & Years']
2020 County Health Rankings California Data - v1_0.xlsx | ['Introduction', 'Outcomes & Factors Rankings', 'Outcomes & Factors SubRankings', 'Ranked Measure Data', 'Additional Measure Data', 'Ranked Measure Sources & Years', 'Addtl Measure Sources & Years']
2021 County Health Rankings California Data - v1.xlsx | ['Introduction', 'Outcomes & Factors Rankings', 'Outcomes & Factors SubRankings', 'Ranked Measure Data', 'Additional Measure Data', 'Ranked Measure Sources & Years', 'Addtl Measure Sources & Years']
2016 County Health Rankings California Data - v3.xls | ['Introduction', 'Outcomes & Factors Rankings', 'Outcomes & Factors SubRankings', 'Ranked Measure Data', 'Additional Measure Data', 'Ranked Measure Sources & Years', 'Addtl Measure Sources & Years', 'Sheet1']
2019 County Health Rankings California Data - v1_0.xls | ['Introduction', 'Outcomes & Factors Rankings', 'Outcomes & Factors SubRankings', 'Ranked Measure Data', 'Additional Measure Data', 'Ranked Measure Sources & Years', 'Addtl Measure Sources & Years']
2024 County Health Rankings California Data - v2.xlsx | ['Introduction', 'Select Measure Data', 'Select Measure Sources & Years', 'Additional Measure Data', 'Addtl Measure Sources & Years', 'Health Outcomes & Factors']
2022 County Health Rankings California Data - v2.xlsx | ['Introduction', 'Outcomes & Factors Rankings', 'Outcomes & Factors SubRankings', 'Ranked Measure Data', 'Additional Measure Data', 'Ranked Measure Sources & Years', 'Addtl Measure Sources & Years']

In [12]:
# Load 2016 CHR file
file_path = '../data/raw/county_health_rankings/2016 County Health Rankings California Data - v3.xls'

df_2016 = pd.read_excel(
    file_path,
    sheet_name='Ranked Measure Data',
    header=[0, 1]  # Multi-row header based on what we saw
)

# Inspect
print('Shape:', df_2016.shape)
print('\nColumn names:')
for col in df_2016.columns:
    print(col)

Shape: (61, 156)

Column names:
('Unnamed: 0_level_0', 'FIPS')
('Unnamed: 1_level_0', 'State')
('Unnamed: 2_level_0', 'County')
('Premature death', '# Deaths')
('Premature death', 'Years of Potential Life Lost Rate')
('Premature death', '95% CI - Low')
('Premature death', '95% CI - High')
('Premature death', 'Z-Score')
('Poor or fair health', '% Fair/Poor')
('Poor or fair health', '95% CI - Low')
('Poor or fair health', '95% CI - High')
('Poor or fair health', 'Z-Score')
('Poor physical health days', 'Physically Unhealthy Days')
('Poor physical health days', '95% CI - Low')
('Poor physical health days', '95% CI - High')
('Poor physical health days', 'Z-Score')
('Poor mental health days', 'Mentally Unhealthy Days')
('Poor mental health days', '95% CI - Low')
('Poor mental health days', '95% CI - High')
('Poor mental health days', 'Z-Score')
('Low birthweight', 'Unreliable')
('Low birthweight', '# Low Birthweight Births')
('Low birthweight', '# Live Births')
('Low birthweight', '% LBW')
('Low birthweight', '95% CI - Low')
('Low birthweight', '95% CI - High')
('Low birthweight', 'Z-Score')
('Adult smoking', '% Smokers')
('Adult smoking', '95% CI - Low')
('Adult smoking', '95% CI - High')
('Adult smoking', 'Z-Score')
('Adult obesity', '% Obese')
('Adult obesity', '95% CI - Low')
('Adult obesity', '95% CI - High')
('Adult obesity', 'Z-Score')
('Food environment index', 'Food Environment Index')
('Food environment index', 'Z-Score')
('Physical inactivity', '% Physically Inactive')
('Physical inactivity', '95% CI - Low')
('Physical inactivity', '95% CI - High')
('Physical inactivity', 'Z-Score')
('Access to exercise opportunities', '% With Access')
('Access to exercise opportunities', 'Z-Score')
('Excessive drinking', '% Excessive Drinking')
('Excessive drinking', '95% CI - Low')
('Excessive drinking', '95% CI - High')
('Excessive drinking', 'Z-Score')
('Alcohol-impaired driving deaths', '# Alcohol-Impaired Driving Deaths')
('Alcohol-impaired driving deaths', '# Driving Deaths')
('Alcohol-impaired driving deaths', '% Alcohol-Impaired')
('Alcohol-impaired driving deaths', '95% CI - Low')
('Alcohol-impaired driving deaths', '95% CI - High')
('Alcohol-impaired driving deaths', 'Z-Score')
('Sexually transmitted infections', '# Chlamydia Cases')
('Sexually transmitted infections', 'Chlamydia Rate')
('Sexually transmitted infections', 'Z-Score')
('Teen births', 'Teen Births')
('Teen births', 'Teen Population')
('Teen births', 'Teen Birth Rate')
('Teen births', '95% CI - Low')
('Teen births', '95% CI - High')
('Teen births', 'Z-Score')
('Uninsured', '# Uninsured')
('Uninsured', '% Uninsured')
('Uninsured', '95% CI - Low')
('Uninsured', '95% CI - High')
('Uninsured', 'Z-Score')
('Primary care physicians', '# Primary Care Physicians')
('Primary care physicians', 'PCP Rate')
('Primary care physicians', 'PCP Ratio')
('Primary care physicians', 'Z-Score')
('Dentists', '# Dentists')
('Dentists', 'Dentist Rate')
('Dentists', 'Dentist Ratio')
('Dentists', 'Z-Score')
('Mental health providers^', '# Mental Health Providers')
('Mental health providers^', 'MHP Rate')
('Mental health providers^', 'MHP Ratio')
('Previous Mental health providers data -- used to calculate rankings^', '# Mental Health Providers')
('Previous Mental health providers data -- used to calculate rankings^', 'MHP Rate')
('Previous Mental health providers data -- used to calculate rankings^', 'MHP Ratio')
('Previous Mental health providers data -- used to calculate rankings^', 'Z-Score')
('Preventable hospital stays', '# Medicare Enrollees')
('Preventable hospital stays', 'Preventable Hosp. Rate')
('Preventable hospital stays', '95% CI - Low')
('Preventable hospital stays', '95% CI - High')
('Preventable hospital stays', 'Z-Score')
('Diabetic monitoring', '# Diabetics')
('Diabetic monitoring', '% Receiving HbA1c')
('Diabetic monitoring', '95% CI - Low')
('Diabetic monitoring', '95% CI - High')
('Diabetic monitoring', 'Z-Score')
('Mammography screening', '# Medicare Enrollees')
('Mammography screening', '% Mammography')
('Mammography screening', '95% CI - Low')
('Mammography screening', '95% CI - High')
('Mammography screening', 'Z-Score')
('High school graduation', 'Cohort Size')
('High school graduation', 'Graduation Rate')
('High school graduation', 'Z-Score')
('Some college', '# Some College')
('Some college', 'Population')
('Some college', '% Some College')
('Some college', '95% CI - Low')
('Some college', '95% CI - High')
('Some college', 'Z-Score')
('Unemployment', '# Unemployed')
('Unemployment', 'Labor Force')
('Unemployment', '% Unemployed')
('Unemployment', 'Z-Score')
('Children in poverty', '# Children in Poverty')
('Children in poverty', '% Children in Poverty')
('Children in poverty', '95% CI - Low')
('Children in poverty', '95% CI - High')
('Children in poverty', 'Z-Score')
('Income inequality', '80th Percentile Income')
('Income inequality', '20th Percentile Income')
('Income inequality', 'Income Ratio')
('Income inequality', 'Z-Score')
('Children in single-parent households', '# Single-Parent Households')
('Children in single-parent households', '# Households')
('Children in single-parent households', '% Single-Parent Households')
('Children in single-parent households', '95% CI - Low')
('Children in single-parent households', '95% CI - High')
('Children in single-parent households', 'Z-Score')
('Social associations', '# Associations')
('Social associations', 'Association Rate')
('Social associations', 'Z-Score')
('Violent crime', '# Violent Crimes')
('Violent crime', 'Violent Crime Rate')
('Violent crime', 'Z-Score')
('Injury deaths', '# Injury Deaths')
('Injury deaths', 'Injury Death Rate')
('Injury deaths', '95% CI - Low')
('Injury deaths', '95% CI - High')
('Injury deaths', 'Z-Score')
('Air pollution - particulate matter', 'Average Daily PM2.5')
('Air pollution - particulate matter', 'Z-Score')
('Drinking water violations', 'Presence of violation')
('Drinking water violations', 'Z-Score')
('Severe housing problems', '# Households with Severe Problems')
('Severe housing problems', '% Severe Housing Problems')
('Severe housing problems', '95% CI - Low')
('Severe housing problems', '95% CI - High')
('Severe housing problems', 'Z-Score')
('Driving alone to work', '# Drive Alone')
('Driving alone to work', '# Workers')
('Driving alone to work', '% Drive Alone')
('Driving alone to work', '95% CI - Low')
('Driving alone to work', '95% CI - High')
('Driving alone to work', 'Z-Score')
('Long commute - driving alone', '# Workers who Drive Alone')
('Long commute - driving alone', '% Long Commute - Drives Alone')
('Long commute - driving alone', '95% CI - Low')
('Long commute - driving alone', '95% CI - High')
('Long commute - driving alone', 'Z-Score')

In [13]:
for f in files:
    if '2025' in f:
        continue
    file_path = '../data/raw/county_health_rankings/' + f
    xl = pd.ExcelFile(file_path)
    sheet = 'Select Measure Data' if '2024' in f else 'Ranked Measure Data'
    df_year = pd.read_excel(file_path, sheet_name=sheet, header=[0,1])
    unique_cols = []
    for col in df_year.columns:
        if col[0] not in unique_cols:
            unique_cols.append(col[0])
    print(f, '|', unique_cols)

2023 County Health Rankings California Data - v3.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature Death', 'Poor or Fair Health', 'Poor Physical Health Days', 'Poor Mental Health Days', 'Low Birthweight', 'Adult Smoking', 'Adult Obesity', 'Food Environment Index', 'Physical Inactivity', 'Access to Exercise Opportunities', 'Excessive Drinking', 'Alcohol-Impaired Driving Deaths', 'Sexually Transmitted Infections', 'Teen Births', 'Uninsured', 'Primary Care Physicians', 'Dentists', 'Mental Health Providers', 'Preventable Hospital Stays', 'Mammography Screening', 'Flu Vaccinations', 'High School Completion', 'Some College', 'Unemployment', 'Children in Poverty', 'Income Inequality', 'Children in Single-Parent Households', 'Social Associations', 'Injury Deaths', 'Air Pollution - Particulate Matter', 'Drinking Water Violations', 'Severe Housing Problems', 'Driving Alone to Work', 'Long Commute - Driving Alone']
2018 County Health Rankings California Data - v3.xls | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Diabetes monitoring', 'Mammography screening', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2017 County Health Rankings California Data - v2.xls | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Diabetes monitoring', 'Mammography screening', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2020 County Health Rankings California Data - v1_0.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Mammography screening', 'Flu vaccinations', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2021 County Health Rankings California Data - v1.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Mammography screening', 'Flu vaccinations', 'High school completion', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2016 County Health Rankings California Data - v3.xls | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers^', 'Previous Mental health providers data -- used to calculate rankings^', 'Preventable hospital stays', 'Diabetic monitoring', 'Mammography screening', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2019 County Health Rankings California Data - v1_0.xls | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Mammography screening', 'Flu vaccinations', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2024 County Health Rankings California Data - v2.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature Death', 'Poor or Fair Health', 'Poor Physical Health Days', 'Poor Mental Health Days', 'Low Birthweight', 'Adult Smoking', 'Adult Obesity', 'Food Environment Index', 'Physical Inactivity', 'Access to Exercise Opportunities', 'Excessive Drinking', 'Alcohol-Impaired Driving Deaths', 'Sexually Transmitted Infections', 'Teen Births', 'Uninsured', 'Primary Care Physicians', 'Dentists', 'Mental Health Providers', 'Preventable Hospital Stays', 'Mammography Screening', 'Flu Vaccinations', 'High School Completion', 'Some College', 'Unemployment', 'Children in Poverty', 'Income Inequality', 'Children in Single-Parent Households', 'Social Associations', 'Injury Deaths', 'Air Pollution - Particulate Matter', 'Drinking Water Violations', 'Severe Housing Problems', 'Driving Alone to Work', 'Long Commute - Driving Alone']
2022 County Health Rankings California Data - v2.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Mammography screening', 'Flu vaccinations', 'High school completion', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']

In [16]:
# check column name consistency at first part of tuple

for f in files:
    if '2025' in f:
        continue
    file_path = '../data/raw/county_health_rankings/' + f

    sheet = 'Select Measure Data' if '2024' in f else 'Ranked Measure Data'
    df_year = pd.read_excel(file_path, sheet_name=sheet, header=[0,1])
    unique_cols = []
    for col in df_year.columns:
        if col[0] not in unique_cols:
            unique_cols.append(col[0])
    print(f, '|', unique_cols)

2023 County Health Rankings California Data - v3.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature Death', 'Poor or Fair Health', 'Poor Physical Health Days', 'Poor Mental Health Days', 'Low Birthweight', 'Adult Smoking', 'Adult Obesity', 'Food Environment Index', 'Physical Inactivity', 'Access to Exercise Opportunities', 'Excessive Drinking', 'Alcohol-Impaired Driving Deaths', 'Sexually Transmitted Infections', 'Teen Births', 'Uninsured', 'Primary Care Physicians', 'Dentists', 'Mental Health Providers', 'Preventable Hospital Stays', 'Mammography Screening', 'Flu Vaccinations', 'High School Completion', 'Some College', 'Unemployment', 'Children in Poverty', 'Income Inequality', 'Children in Single-Parent Households', 'Social Associations', 'Injury Deaths', 'Air Pollution - Particulate Matter', 'Drinking Water Violations', 'Severe Housing Problems', 'Driving Alone to Work', 'Long Commute - Driving Alone']
2018 County Health Rankings California Data - v3.xls | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Diabetes monitoring', 'Mammography screening', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2017 County Health Rankings California Data - v2.xls | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Diabetes monitoring', 'Mammography screening', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2020 County Health Rankings California Data - v1_0.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Mammography screening', 'Flu vaccinations', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2021 County Health Rankings California Data - v1.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Mammography screening', 'Flu vaccinations', 'High school completion', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2016 County Health Rankings California Data - v3.xls | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers^', 'Previous Mental health providers data -- used to calculate rankings^', 'Preventable hospital stays', 'Diabetic monitoring', 'Mammography screening', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2019 County Health Rankings California Data - v1_0.xls | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Mammography screening', 'Flu vaccinations', 'High school graduation', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']
2024 County Health Rankings California Data - v2.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature Death', 'Poor or Fair Health', 'Poor Physical Health Days', 'Poor Mental Health Days', 'Low Birthweight', 'Adult Smoking', 'Adult Obesity', 'Food Environment Index', 'Physical Inactivity', 'Access to Exercise Opportunities', 'Excessive Drinking', 'Alcohol-Impaired Driving Deaths', 'Sexually Transmitted Infections', 'Teen Births', 'Uninsured', 'Primary Care Physicians', 'Dentists', 'Mental Health Providers', 'Preventable Hospital Stays', 'Mammography Screening', 'Flu Vaccinations', 'High School Completion', 'Some College', 'Unemployment', 'Children in Poverty', 'Income Inequality', 'Children in Single-Parent Households', 'Social Associations', 'Injury Deaths', 'Air Pollution - Particulate Matter', 'Drinking Water Violations', 'Severe Housing Problems', 'Driving Alone to Work', 'Long Commute - Driving Alone']
2022 County Health Rankings California Data - v2.xlsx | ['Unnamed: 0_level_0', 'Unnamed: 1_level_0', 'Unnamed: 2_level_0', 'Premature death', 'Poor or fair health', 'Poor physical health days', 'Poor mental health days', 'Low birthweight', 'Adult smoking', 'Adult obesity', 'Food environment index', 'Physical inactivity', 'Access to exercise opportunities', 'Excessive drinking', 'Alcohol-impaired driving deaths', 'Sexually transmitted infections', 'Teen births', 'Uninsured', 'Primary care physicians', 'Dentists', 'Mental health providers', 'Preventable hospital stays', 'Mammography screening', 'Flu vaccinations', 'High school completion', 'Some college', 'Unemployment', 'Children in poverty', 'Income inequality', 'Children in single-parent households', 'Social associations', 'Violent crime', 'Injury deaths', 'Air pollution - particulate matter', 'Drinking water violations', 'Severe housing problems', 'Driving alone to work', 'Long commute - driving alone']

In [ ]:
# check column name consistency at second part of tuple

target_categories = ['premature death', 'poor mental health days', 
                     'preventable hospital stays', 'children in poverty', 
                     'low birthweight']
   

for f in files:
    if '2025' in f:
        continue
    file_path = '../data/raw/county_health_rankings/' + f
    sheet = 'Select Measure Data' if '2024' in f else 'Ranked Measure Data'
    df_year = pd.read_excel(file_path, sheet_name=sheet, header=[0,1])
    unique_cols = []
    for col in df_year.columns:
        if col[0].lower() in target_categories:
            if col[1] not in unique_cols:
                unique_cols.append(col[1])
    print(f, '|', unique_cols)

2023 County Health Rankings California Data - v3.xlsx | ['Unreliable', 'Deaths', 'Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'Z-Score', 'YPLL Rate (AIAN)', 'YPLL Rate (AIAN) 95% CI - Low', 'YPLL Rate (AIAN) 95% CI - High', 'YPLL Rate (AIAN) Unreliable', 'YPLL Rate (Asian)', 'YPLL Rate (Asian) 95% CI - Low', 'YPLL Rate (Asian) 95% CI - High', 'YPLL Rate (Asian) Unreliable', 'YPLL Rate (Black)', 'YPLL Rate (Black) 95% CI - Low', 'YPLL Rate (Black) 95% CI - High', 'YPLL Rate (Black) Unreliable', 'YPLL Rate (Hispanic)', 'YPLL Rate (Hispanic) 95% CI - Low', 'YPLL Rate (Hispanic) 95% CI - High', 'YPLL Rate (Hispanic) Unreliable', 'YPLL Rate (White)', 'YPLL Rate (White) 95% CI - Low', 'YPLL Rate (White) 95% CI - High', 'YPLL Rate (White) Unreliable', 'Average Number of Mentally Unhealthy Days', '% Low Birthweight', '% LBW (AIAN)', '% LBW (AIAN) 95% CI - Low', '% LBW (AIAN) 95% CI - High', '% LBW (Asian)', '% LBW (Asian) 95% CI - Low', '% LBW (Asian) 95% CI - High', '% LBW (Black)', '% LBW (Black) 95% CI - Low', '% LBW (Black) 95% CI - High', '% LBW (Hispanic)', '% LBW (Hispanic) 95% CI - Low', '% LBW (Hispanic) 95% CI - High', '% LBW (White)', '% LBW (White) 95% CI - Low', '% LBW (White) 95% CI - High', 'Preventable Hospitalization Rate', 'Preventable Hosp. Rate (AIAN)', 'Preventable Hosp. Rate (Asian)', 'Preventable Hosp. Rate (Black)', 'Preventable Hosp. Rate (Hispanic)', 'Preventable Hosp. Rate (White)', '% Children in Poverty', '% Children in Poverty (AIAN)', '% Children in Poverty (Asian)', '% Children in Poverty (Black)', '% Children in Poverty (Hispanic)', '% Children in Poverty (White)']
2018 County Health Rankings California Data - v3.xls | ['Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'Z-Score', 'Years of Potential Life Lost Rate (Black)', 'Years of Potential Life Lost Rate (Hispanic)', 'Years of Potential Life Lost Rate (White)', 'Mentally Unhealthy Days', 'Unreliable', '% LBW', '% LBW (Black)', '% LBW (Hispanic)', '% LBW (White)', '# Medicare Enrollees', 'Preventable Hosp. Rate', '% Children in Poverty', '% Children in Poverty (Black)', '% Children in Poverty (Hispanic)', '% Children in Poverty (White)']
2017 County Health Rankings California Data - v2.xls | ['# Deaths', 'Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'Z-Score', 'Mentally Unhealthy Days', 'Unreliable', '# Low Birthweight Births', '# Live Births', '% LBW', '# Medicare Enrollees', 'Preventable Hosp. Rate', 'Preventable Hosp. Rate (white)', 'Preventable Hosp. Rate (black)', '% Children in Poverty', '% Children in Poverty - Black', '% Children in Poverty - Hispanic', '% Children in Poverty - White']
2020 County Health Rankings California Data - v1_0.xlsx | ['Deaths', 'Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'Z-Score', 'YPLL Rate (AIAN)', 'YPLL Rate (AIAN) 95% CI - Low', 'YPLL Rate (AIAN) 95% CI - High', 'YPLL Rate (Asian)', 'YPLL Rate (Asian) 95% CI - Low', 'YPLL Rate (Asian) 95% CI - High', 'YPLL Rate (Black)', 'YPLL Rate (Black) 95% CI - Low', 'YPLL Rate (Black) 95% CI - High', 'YPLL Rate (Hispanic)', 'YPLL Rate (Hispanic) 95% CI - Low', 'YPLL Rate (Hispanic) 95% CI - High', 'YPLL Rate (White)', 'YPLL Rate (White) 95% CI - Low', 'YPLL Rate (White) 95% CI - High', 'Average Number of Mentally Unhealthy Days', 'Unreliable', '% Low Birthweight', '% LBW (AIAN)', '% LBW (AIAN) 95% CI - Low', '% LBW (AIAN) 95% CI - High', '% LBW (Asian)', '% LBW (Asian) 95% CI - Low', '% LBW (Asian) 95% CI - High', '% LBW (Black)', '% LBW (Black) 95% CI - Low', '% LBW (Black) 95% CI - High', '% LBW (Hispanic)', '% LBW (Hispanic) 95% CI - Low', '% LBW (Hispanic) 95% CI - High', '% LBW (White)', '% LBW (White) 95% CI - Low', '% LBW (White) 95% CI - High', 'Preventable Hospitalization Rate', 'Preventable Hosp. Rate (AIAN)', 'Preventable Hosp. Rate (Asian)', 'Preventable Hosp. Rate (Black)', 'Preventable Hosp. Rate (Hispanic)', 'Preventable Hosp. Rate (White)', '% Children in Poverty', '% Children in Poverty (AIAN)', '% Children in Poverty (Asian)', '% Children in Poverty (Black)', '% Children in Poverty (Hispanic)', '% Children in Poverty (White)']
2021 County Health Rankings California Data - v1.xlsx | ['Unreliable', 'Deaths', 'Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'Z-Score', 'YPLL Rate (AIAN)', 'YPLL Rate (AIAN) 95% CI - Low', 'YPLL Rate (AIAN) 95% CI - High', 'YPLL Rate (AIAN) Unreliable', 'YPLL Rate (Asian)', 'YPLL Rate (Asian) 95% CI - Low', 'YPLL Rate (Asian) 95% CI - High', 'YPLL Rate (Asian) Unreliable', 'YPLL Rate (Black)', 'YPLL Rate (Black) 95% CI - Low', 'YPLL Rate (Black) 95% CI - High', 'YPLL Rate (Black) Unreliable', 'YPLL Rate (Hispanic)', 'YPLL Rate (Hispanic) 95% CI - Low', 'YPLL Rate (Hispanic) 95% CI - High', 'YPLL Rate (Hispanic) Unreliable', 'YPLL Rate (White)', 'YPLL Rate (White) 95% CI - Low', 'YPLL Rate (White) 95% CI - High', 'YPLL Rate (White) Unreliable', 'Average Number of Mentally Unhealthy Days', '% Low birthweight', '% LBW (AIAN)', '% LBW (AIAN) 95% CI - Low', '% LBW (AIAN) 95% CI - High', '% LBW (Asian)', '% LBW (Asian) 95% CI - Low', '% LBW (Asian) 95% CI - High', '% LBW (Black)', '% LBW (Black) 95% CI - Low', '% LBW (Black) 95% CI - High', '% LBW (Hispanic)', '% LBW (Hispanic) 95% CI - Low', '% LBW (Hispanic) 95% CI - High', '% LBW (White)', '% LBW (White) 95% CI - Low', '% LBW (White) 95% CI - High', 'Preventable Hospitalization Rate', 'Preventable Hosp. Rate (AIAN)', 'Preventable Hosp. Rate (Asian)', 'Preventable Hosp. Rate (Black)', 'Preventable Hosp. Rate (Hispanic)', 'Preventable Hosp. Rate (White)', '% Children in Poverty', '% Children in Poverty (AIAN)', '% Children in Poverty (Asian)', '% Children in Poverty (Black)', '% Children in Poverty (Hispanic)', '% Children in Poverty (White)']
2016 County Health Rankings California Data - v3.xls | ['# Deaths', 'Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'Z-Score', 'Mentally Unhealthy Days', 'Unreliable', '# Low Birthweight Births', '# Live Births', '% LBW', '# Medicare Enrollees', 'Preventable Hosp. Rate', '# Children in Poverty', '% Children in Poverty']
2019 County Health Rankings California Data - v1_0.xls | ['Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'Z-Score', 'YPLL Rate (Black)', 'YPLL Rate (Hispanic)', 'YPLL Rate (White)', 'Mentally Unhealthy Days', 'Unreliable', '% LBW', '% LBW (Black)', '% LBW (Hispanic)', '% LBW (White)', 'Preventable Hosp. Rate', 'Preventable Hosp. Rate (Black)', 'Preventable Hosp. Rate (Hispanic)', 'Preventable Hosp. Rate (White)', '% Children in Poverty', '% Children in Poverty (Black)', '% Children in Poverty (Hispanic)', '% Children in Poverty (White)']
2024 County Health Rankings California Data - v2.xlsx | ['Unreliable', 'Deaths', 'Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'National Z-Score', 'YPLL Rate (Hispanic (all races))', 'YPLL Rate (Hispanic (all races)) 95% CI - Low', 'YPLL Rate (Hispanic (all races)) 95% CI - High', 'YPLL Rate (Hispanic (all races)) Unreliable', 'YPLL Rate (Non-Hispanic AIAN)', 'YPLL Rate (Non-Hispanic AIAN) 95% CI - Low', 'YPLL Rate (Non-Hispanic AIAN) 95% CI - High', 'YPLL Rate (Non-Hispanic AIAN) Unreliable', 'YPLL Rate (Non-Hispanic Asian)', 'YPLL Rate (Non-Hispanic Asian) 95% CI - Low', 'YPLL Rate (Non-Hispanic Asian) 95% CI - High', 'YPLL Rate (Non-Hispanic Asian) Unreliable', 'YPLL Rate (Non-Hispanic Black)', 'YPLL Rate (Non-Hispanic Black) 95% CI - Low', 'YPLL Rate (Non-Hispanic Black) 95% CI - High', 'YPLL Rate (Non-Hispanic Black) Unreliable', 'YPLL Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander)', 'YPLL Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low', 'YPLL Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High', 'YPLL Rate (Non-Hispanic Native Hawaiian and Other Pacific Islander) Unreliable', 'YPLL Rate (Non-Hispanic 2+ races)', 'YPLL Rate (Non-Hispanic 2+ races) 95% CI - Low', 'YPLL Rate (Non-Hispanic 2+ races) 95% CI - High', 'YPLL Rate (Non-Hispanic 2+ races) Unreliable', 'YPLL Rate (Non-Hispanic White)', 'YPLL Rate (Non-Hispanic White) 95% CI - Low', 'YPLL Rate (Non-Hispanic White) 95% CI - High', 'YPLL Rate (Non-Hispanic White) Unreliable', 'Average Number of Mentally Unhealthy Days', '% Low Birthweight', '% LBW (Hispanic (all races))', '% LBW (Hispanic (all races)) 95% CI - Low', '% LBW (Hispanic (all races)) 95% CI - High', '% LBW (Non-Hispanic AIAN)', '% LBW (Non-Hispanic AIAN) 95% CI - Low', '% LBW (Non-Hispanic AIAN) 95% CI - High', '% LBW (Non-Hispanic Asian)', '% LBW (Non-Hispanic Asian) 95% CI - Low', '% LBW (Non-Hispanic Asian) 95% CI - High', '% LBW (Non-Hispanic Black)', '% LBW (Non-Hispanic Black) 95% CI - Low', '% LBW (Non-Hispanic Black) 95% CI - High', '% LBW (Non-Hispanic Native Hawaiian and Other Pacific Islander)', '% LBW (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - Low', '% LBW (Non-Hispanic Native Hawaiian and Other Pacific Islander) 95% CI - High', '% LBW (Non-Hispanic 2+ races)', '% LBW (Non-Hispanic 2+ races) 95% CI - Low', '% LBW (Non-Hispanic 2+ races) 95% CI - High', '% LBW (Non-Hispanic White)', '% LBW (Non-Hispanic White) 95% CI - Low', '% LBW (Non-Hispanic White) 95% CI - High', 'Preventable Hospitalization Rate', 'Preventable Hosp. Rate (AIAN)', 'Preventable Hosp. Rate (Asian)', 'Preventable Hosp. Rate (Black)', 'Preventable Hosp. Rate (Hispanic)', 'Preventable Hosp. Rate (White)', '% Children in Poverty', '% Children in Poverty (AIAN)', '% Children in Poverty (Asian)', '% Children in Poverty (Black)', '% Children in Poverty (Hispanic)', '% Children in Poverty (White)']
2022 County Health Rankings California Data - v2.xlsx | ['Unreliable', 'Deaths', 'Years of Potential Life Lost Rate', '95% CI - Low', '95% CI - High', 'Z-Score', 'YPLL Rate (AIAN)', 'YPLL Rate (AIAN) 95% CI - Low', 'YPLL Rate (AIAN) 95% CI - High', 'YPLL Rate (AIAN) Unreliable', 'YPLL Rate (Asian)', 'YPLL Rate (Asian) 95% CI - Low', 'YPLL Rate (Asian) 95% CI - High', 'YPLL Rate (Asian) Unreliable', 'YPLL Rate (Black)', 'YPLL Rate (Black) 95% CI - Low', 'YPLL Rate (Black) 95% CI - High', 'YPLL Rate (Black) Unreliable', 'YPLL Rate (Hispanic)', 'YPLL Rate (Hispanic) 95% CI - Low', 'YPLL Rate (Hispanic) 95% CI - High', 'YPLL Rate (Hispanic) Unreliable', 'YPLL Rate (white)', 'YPLL Rate (white) 95% CI - Low', 'YPLL Rate (white) 95% CI - High', 'YPLL Rate (white) Unreliable', 'Average Number of Mentally Unhealthy Days', '% Low birthweight', '% LBW (AIAN)', '% LBW (AIAN) 95% CI - Low', '% LBW (AIAN) 95% CI - High', '% LBW (Asian)', '% LBW (Asian) 95% CI - Low', '% LBW (Asian) 95% CI - High', '% LBW (Black)', '% LBW (Black) 95% CI - Low', '% LBW (Black) 95% CI - High', '% LBW (Hispanic)', '% LBW (Hispanic) 95% CI - Low', '% LBW (Hispanic) 95% CI - High', '% LBW (white)', '% LBW (white) 95% CI - Low', '% LBW (white) 95% CI - High', 'Preventable Hospitalization Rate', 'Preventable Hosp. Rate (AIAN)', 'Preventable Hosp. Rate (Asian)', 'Preventable Hosp. Rate (Black)', 'Preventable Hosp. Rate (Hispanic)', 'Preventable Hosp. Rate (white)', '% Children in Poverty', '% Children in Poverty (AIAN)', '% Children in Poverty (Asian)', '% Children in Poverty (Black)', '% Children in Poverty (Hispanic)', '% Children in Poverty (white)']

Inspection of second-level tuple column names across all years reveals the 
following:

Consistent across all years:
- Premature Death: 'Years of Potential Life Lost Rate'
- Children in Poverty: '% Children in Poverty'

Inconsistent — require standardization in cleaning:
- Poor Mental Health Days: 'Mentally Unhealthy Days' (2016–2019) → 
  'Average Number of Mentally Unhealthy Days' (2020–2024)
- Preventable Hospital Stays: 'Preventable Hosp. Rate' (2016–2019) → 
  'Preventable Hospitalization Rate' (2020–2024)
- Low Birthweight: '% LBW' (2016–2019) → '% Low Birthweight' (2020–2024)

Note: capitalization of first-level tuple names also inconsistent — 
lowercase 2016–2022, title case 2023–2024. Both issues to be resolved 
in cleaning notebook.

In [21]:
# view income data files

print(os.getcwd())


files = os.listdir('../data/raw/census_acs')
for f in sorted(files):
    print(f)

/Users/douglas/Documents/GitHub/SDOH_Housing_Health_CA/notebooks
.DS_Store
ACSST1Y2016.S1901-Column-Metadata.csv
ACSST1Y2016.S1901-Data.csv
ACSST1Y2017.S1901-Column-Metadata.csv
ACSST1Y2017.S1901-Data.csv
ACSST1Y2018.S1901-Column-Metadata.csv
ACSST1Y2018.S1901-Data.csv
ACSST1Y2019.S1901-Column-Metadata.csv
ACSST1Y2019.S1901-Data.csv
ACSST1Y2021.S1901-Column-Metadata.csv
ACSST1Y2021.S1901-Data.csv
ACSST1Y2022.S1901-Column-Metadata.csv
ACSST1Y2022.S1901-Data.csv
ACSST1Y2023.S1901-Column-Metadata.csv
ACSST1Y2023.S1901-Data.csv
ACSST1Y2024.S1901-Column-Metadata.csv
ACSST1Y2024.S1901-Data.csv

In [ ]:
# Load 2024 ACSST income data file
file_path = '../data/raw/census_acs/ACSST1Y2024.S1901-Data.csv'

income_df_2024 = pd.read_csv(file_path,
    header=[0]  # Multi-row header based on what we saw
    )

# Inspect the file
print('Shape:', income_df_2024.shape)
print('\nColumn names:')
for col in income_df_2024.columns:
    print(col)

Shape: (905, 131)

Column names:
GEO_ID
NAME
S1901_C01_001E
S1901_C01_001M
S1901_C01_002E
S1901_C01_002M
S1901_C01_003E
S1901_C01_003M
S1901_C01_004E
S1901_C01_004M
S1901_C01_005E
S1901_C01_005M
S1901_C01_006E
S1901_C01_006M
S1901_C01_007E
S1901_C01_007M
S1901_C01_008E
S1901_C01_008M
S1901_C01_009E
S1901_C01_009M
S1901_C01_010E
S1901_C01_010M
S1901_C01_011E
S1901_C01_011M
S1901_C01_012E
S1901_C01_012M
S1901_C01_013E
S1901_C01_013M
S1901_C01_014E
S1901_C01_014M
S1901_C01_015E
S1901_C01_015M
S1901_C01_016E
S1901_C01_016M
S1901_C02_001E
S1901_C02_001M
S1901_C02_002E
S1901_C02_002M
S1901_C02_003E
S1901_C02_003M
S1901_C02_004E
S1901_C02_004M
S1901_C02_005E
S1901_C02_005M
S1901_C02_006E
S1901_C02_006M
S1901_C02_007E
S1901_C02_007M
S1901_C02_008E
S1901_C02_008M
S1901_C02_009E
S1901_C02_009M
S1901_C02_010E
S1901_C02_010M
S1901_C02_011E
S1901_C02_011M
S1901_C02_012E
S1901_C02_012M
S1901_C02_013E
S1901_C02_013M
S1901_C02_014E
S1901_C02_014M
S1901_C02_015E
S1901_C02_015M
S1901_C02_016E
S1901_C02_016M
S1901_C03_001E
S1901_C03_001M
S1901_C03_002E
S1901_C03_002M
S1901_C03_003E
S1901_C03_003M
S1901_C03_004E
S1901_C03_004M
S1901_C03_005E
S1901_C03_005M
S1901_C03_006E
S1901_C03_006M
S1901_C03_007E
S1901_C03_007M
S1901_C03_008E
S1901_C03_008M
S1901_C03_009E
S1901_C03_009M
S1901_C03_010E
S1901_C03_010M
S1901_C03_011E
S1901_C03_011M
S1901_C03_012E
S1901_C03_012M
S1901_C03_013E
S1901_C03_013M
S1901_C03_014E
S1901_C03_014M
S1901_C03_015E
S1901_C03_015M
S1901_C03_016E
S1901_C03_016M
S1901_C04_001E
S1901_C04_001M
S1901_C04_002E
S1901_C04_002M
S1901_C04_003E
S1901_C04_003M
S1901_C04_004E
S1901_C04_004M
S1901_C04_005E
S1901_C04_005M
S1901_C04_006E
S1901_C04_006M
S1901_C04_007E
S1901_C04_007M
S1901_C04_008E
S1901_C04_008M
S1901_C04_009E
S1901_C04_009M
S1901_C04_010E
S1901_C04_010M
S1901_C04_011E
S1901_C04_011M
S1901_C04_012E
S1901_C04_012M
S1901_C04_013E
S1901_C04_013M
S1901_C04_014E
S1901_C04_014M
S1901_C04_015E
S1901_C04_015M
S1901_C04_016E
S1901_C04_016M
Unnamed: 130

In [28]:
income_df_2024.head(3)

,GEO_ID,NAME,S1901_C01_001E,S1901_C01_001M,S1901_C01_002E,S1901_C01_002M,S1901_C01_003E,S1901_C01_003M,S1901_C01_004E,S1901_C01_004M,S1901_C01_005E,S1901_C01_005M,S1901_C01_006E,S1901_C01_006M,S1901_C01_007E,S1901_C01_007M,S1901_C01_008E,S1901_C01_008M,S1901_C01_009E,S1901_C01_009M,S1901_C01_010E,S1901_C01_010M,S1901_C01_011E,S1901_C01_011M,S1901_C01_012E,S1901_C01_012M,S1901_C01_013E,S1901_C01_013M,S1901_C01_014E,S1901_C01_014M,S1901_C01_015E,S1901_C01_015M,S1901_C01_016E,S1901_C01_016M,S1901_C02_001E,S1901_C02_001M,S1901_C02_002E,S1901_C02_002M,S1901_C02_003E,S1901_C02_003M,S1901_C02_004E,S1901_C02_004M,S1901_C02_005E,S1901_C02_005M,S1901_C02_006E,S1901_C02_006M,S1901_C02_007E,S1901_C02_007M,S1901_C02_008E,S1901_C02_008M,S1901_C02_009E,S1901_C02_009M,S1901_C02_010E,S1901_C02_010M,S1901_C02_011E,S1901_C02_011M,S1901_C02_012E,S1901_C02_012M,S1901_C02_013E,S1901_C02_013M,S1901_C02_014E,S1901_C02_014M,S1901_C02_015E,S1901_C02_015M,S1901_C02_016E,S1901_C02_016M,S1901_C03_001E,S1901_C03_001M,S1901_C03_002E,S1901_C03_002M,S1901_C03_003E,S1901_C03_003M,S1901_C03_004E,S1901_C03_004M,S1901_C03_005E,S1901_C03_005M,S1901_C03_006E,S1901_C03_006M,S1901_C03_007E,S1901_C03_007M,S1901_C03_008E,S1901_C03_008M,S1901_C03_009E,S1901_C03_009M,S1901_C03_010E,S1901_C03_010M,S1901_C03_011E,S1901_C03_011M,S1901_C03_012E,S1901_C03_012M,S1901_C03_013E,S1901_C03_013M,S1901_C03_014E,S1901_C03_014M,S1901_C03_015E,S1901_C03_015M,S1901_C03_016E,S1901_C03_016M,S1901_C04_001E,S1901_C04_001M,S1901_C04_002E,S1901_C04_002M,S1901_C04_003E,S1901_C04_003M,S1901_C04_004E,S1901_C04_004M,S1901_C04_005E,S1901_C04_005M,S1901_C04_006E,S1901_C04_006M,S1901_C04_007E,S1901_C04_007M,S1901_C04_008E,S1901_C04_008M,S1901_C04_009E,S1901_C04_009M,S1901_C04_010E,S1901_C04_010M,S1901_C04_011E,S1901_C04_011M,S1901_C04_012E,S1901_C04_012M,S1901_C04_013E,S1901_C04_013M,S1901_C04_014E,S1901_C04_014M,S1901_C04_015E,S1901_C04_015M,S1901_C04_016E,S1901_C04_016M,Unnamed: 130
0,Geography,Geographic Area Name,Estimate!!Households!!Total,Margin of Error!!Households!!Total,"Estimate!!Households!!Total!!Less than $10,000",Margin of Error!!Households!!Total!!Less than ...,"Estimate!!Households!!Total!!$10,000 to $14,999","Margin of Error!!Households!!Total!!$10,000 to...","Estimate!!Households!!Total!!$15,000 to $24,999","Margin of Error!!Households!!Total!!$15,000 to...","Estimate!!Households!!Total!!$25,000 to $34,999","Margin of Error!!Households!!Total!!$25,000 to...","Estimate!!Households!!Total!!$35,000 to $49,999","Margin of Error!!Households!!Total!!$35,000 to...","Estimate!!Households!!Total!!$50,000 to $74,999","Margin of Error!!Households!!Total!!$50,000 to...","Estimate!!Households!!Total!!$75,000 to $99,999","Margin of Error!!Households!!Total!!$75,000 to...","Estimate!!Households!!Total!!$100,000 to $149,999","Margin of Error!!Households!!Total!!$100,000 t...","Estimate!!Households!!Total!!$150,000 to $199,999","Margin of Error!!Households!!Total!!$150,000 t...","Estimate!!Households!!Total!!$200,000 or more","Margin of Error!!Households!!Total!!$200,000 o...",Estimate!!Households!!Median income (dollars),Margin of Error!!Households!!Median income (do...,Estimate!!Households!!Mean income (dollars),Margin of Error!!Households!!Mean income (doll...,Estimate!!Households!!PERCENT ALLOCATED!!House...,Margin of Error!!Households!!PERCENT ALLOCATED...,Estimate!!Households!!PERCENT ALLOCATED!!Famil...,Margin of Error!!Households!!PERCENT ALLOCATED...,Estimate!!Households!!PERCENT ALLOCATED!!Nonfa...,Margin of Error!!Households!!PERCENT ALLOCATED...,Estimate!!Families!!Total,Margin of Error!!Families!!Total,"Estimate!!Families!!Total!!Less than $10,000",Margin of Error!!Families!!Total!!Less than $1...,"Estimate!!Families!!Total!!$10,000 to $14,999","Margin of Error!!Families!!Total!!$10,000 to $...","Estimate!!Families!!Total!!$15,000 to $24,999","Margin of Error!!Families!!Total!!$15,000 to $...","Estimate!!Families!!Total!!$25,000 to $34,999","Margin of Error!!Families!!Total!!$25,000 to $...","Estimate!!Families!!Total!!$35,000 to $49,999","Margin of Error!!Families!!Total!!$35,000 to $...","Estimate!!Families!!Total!!$50,000 to $74,999","Margin of Error!!Families!!Total!!$50,000 to $...","Estimate!!Families!!Total!!$75,000 to $99,999","Margin of Error!!Families!!Total!!$75,000 to $...","Estimate!!Families!!Total!!$100,000 to $149,999","Margin of Error!!Families!!Total!!$100,000 to ...","Estimate!!Families!!Total!!$150,000 to $199,999","Margin of Error!!Families!!Total!!$150,000 to ...","Estimate!!Families!!Total!!$200,000 or more","Margin of Error!!Families!!Total!!$200,000 or ...",Estimate!!Families!!Median income (dollars),Margin of Error!!Families!!Median income (doll...,Estimate!!Families!!Mean income (dollars),Margin of Error!!Families!!Mean income (dollars),Estimate!!Families!!PERCENT ALLOCATED!!Househo...,Margin of Error!!Families!!PERCENT ALLOCATED!!...,Estimate!!Families!!PERCENT ALLOCATED!!Family ...,Margin of Error!!Families!!PERCENT ALLOCATED!!...,Estimate!!Families!!PERCENT ALLOCATED!!Nonfami...,Margin of Error!!Families!!PERCENT ALLOCATED!!...,Estimate!!Married-couple families!!Total,Margin of Error!!Married-couple families!!Total,Estimate!!Married-couple families!!Total!!Less...,Margin of Error!!Married-couple families!!Tota...,"Estimate!!Married-couple families!!Total!!$10,...",Margin of Error!!Married-couple families!!Tota...,"Estimate!!Married-couple families!!Total!!$15,...",Margin of Error!!Married-couple families!!Tota...,"Estimate!!Married-couple families!!Total!!$25,...",Margin of Error!!Married-couple families!!Tota...,"Estimate!!Married-couple families!!Total!!$35,...",Margin of Error!!Married-couple families!!Tota...,"Estimate!!Married-couple families!!Total!!$50,...",Margin of Error!!Married-couple families!!Tota...,"Estimate!!Married-couple families!!Total!!$75,...",Margin of Error!!Married-couple families!!Tota...,Estimate!!Married-couple families!!Total!!$100...,Margin of Error!!Married-couple families!!Tota...,Estimate!!Married-couple families!!Total!!$150...,Margin of Error!!Married-couple families!!Tota...,Estimate!!Married-couple families!!Total!!$200...,Margin of Error!!Married-couple families!!Tota...,Estimate!!Married-couple families!!Median inco...,Margin of Error!!Married-couple families!!Medi...,Estimate!!Married-couple families!!Mean income...,Margin of Error!!Married-couple families!!Mean...,Estimate!!Married-couple families!!PERCENT ALL...,Margin of Error!!Married-couple families!!PERC...,Estimate!!Married-couple families!!PERCENT ALL...,Margin of Error!!Married-couple families!!PERC...,Estimate!!Married-couple families!!PERCENT ALL...,Margin of Error!!Married-couple families!!PERC...,Estimate!!Nonfamily households!!Total,Margin of Error!!Nonfamily households!!Total,Estimate!!Nonfamily households!!Total!!Less th...,Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$10,000...",Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$15,000...",Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$25,000...",Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$35,000...",Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$50,000...",Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$75,000...",Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$100,00...",Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$150,00...",Margin of Error!!Nonfamily households!!Total!!...,"Estimate!!Nonfamily households!!Total!!$200,00...",Margin of Error!!Nonfamily households!!Total!!...,Estimate!!Nonfamily households!!Median income ...,Margin of Error!!Nonfamily households!!Median ...,Estimate!!Nonfamily households!!Mean income (d...,Margin of Error!!Nonfamily households!!Mean in...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,Estimate!!Nonfamily households!!PERCENT ALLOCA...,Margin of Error!!Nonfamily households!!PERCENT...,NaN
1,0400000US06,California,13797638,19379,4.6,0.1,3.0,0.1,5.0,0.1,4.9,0.1,7.9,0.1,13.1,0.2,11.4,0.2,17.9,0.2,11.2,0.2,21.0,0.2,100149,381,140112,691,39.1,(X),(X),(X),(X),(X),9297773,37513,2.9,0.1,1.6,0.1,3.6,0.1,4.2,0.1,7.2,0.2,12.6,0.2,11.5,0.2,19.2,0.2,12.5,0.2,24.8,0.2,113969,828,157192,881,(X),(X),41.6,(X),(X),(X),6599228,37735,1.5,0.1,0.9,0.1,2.5,0.1,2.9,0.1,5.4,0.2,10.4,0.3,10.6,0.2,20.0,0.3,14.5,0.2,31.4,0.3,138170,935,183563,997,(X),(X),(X),(X),(X),(X),4499865,32035,9.1,0.3,6.2,0.2,8.4,0.3,7.3,0.2,10.4,0.3,14.9,0.3,11.1,0.3,14.4,0.3,7.3,0.2,11.0,0.3,63280,844,95264,983,(X),(X),(X),(X),32.1,(X),NaN
2,0500000US01003,"Baldwin County, Alabama",105959,3520,3.3,1.1,3.8,1.3,6.2,1.5,7.6,1.8,9.5,1.7,14.7,2.2,15.4,2.4,19.5,2.8,7.9,1.6,11.9,2.2,82501,5205,105861,6708,37.7,(X),(X),(X),(X),(X),72891,4060,1.2,0.7,2.2,1.4,3.4,1.7,5.5,1.8,7.9,1.9,14.5,2.3,16.3,2.8,23.4,3.3,10.3,2.0,15.1,2.9,97123,7676,123941,8692,(X),(X),38.4,(X),(X),(X),N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,104253,5883,N,N,(X),(X),(X),(X),(X),(X),33068,3273,8.0,3.2,7.4,2.9,12.4,4.1,12.5,4.1,14.2,3.8,18.1,5.0,11.4,4.2,9.3,3.2,2.4,2.3,4.3,2.7,44007,6639,63256,9276,(X),(X),(X),(X),34.7,(X),NaN

The median household income column is identified as 'S1901_C01_012E' 
(Estimate!!Households!!Median income (dollars)).

The Data file contains 904 rows and 131 columns, representing counties 
across all 50 states. California counties can be filtered using the GEO_ID 
column, which begins with '0500000US06' for all 58 California counties.

Note: the Data file uses a single-row header (header=0), unlike CHR which 
required a two-row MultiIndex header. The Column-Metadata file was used as 
a reference to identify the correct column code.

Suppression codes '(X)' and 'N' were observed in the data and will require 
handling in the cleaning notebook.

2020 is absent from the ACS 1-year estimates due to COVID-19 data collection 
disruptions — this is a known gap in the analysis.

In [29]:
# loop checking for income data column 'S1901_C01_012E' in each file year              
files = os.listdir('../data/raw/census_acs')
for f in sorted(files):
    if 'Data' in f:
        file_path = '../data/raw/census_acs/' + f
        df_year = pd.read_csv(file_path, header=0)
        if 'S1901_C01_012E' in df_year.columns:
            print('Found in:', f)
        else:
            print('MISSING in:', f)

Found in: ACSST1Y2016.S1901-Data.csv
Found in: ACSST1Y2017.S1901-Data.csv
Found in: ACSST1Y2018.S1901-Data.csv
Found in: ACSST1Y2019.S1901-Data.csv
Found in: ACSST1Y2021.S1901-Data.csv
Found in: ACSST1Y2022.S1901-Data.csv
Found in: ACSST1Y2023.S1901-Data.csv
Found in: ACSST1Y2024.S1901-Data.csv

Column naming consistency was checked in all 8 target files. The convention of naming the estimated household income variable, 'S1901_C01_012E' has been verified in all years. 
The year 2020 is missing the reporting file due to disruptions arising from the Covid 19 pandemic. This is a noted data limitation.